import React from 'react';
import PropTypes from 'prop-types';
import styles from './styles.scss';

function Header({ selectedJob }) {
  return (
    <div className="container">
      {(!selectedJob) ? (<h1>XIV Bars</h1>) : (<h2>XIV Bars</h2>)}

      <div className={styles.description}>
        <p>A Final Fantasy XIV W Cross HotBar (WXHB) Preview Tool.</p>
        <p>
          Creating the perfect controller setup in-game is clunky and time-consuming. This app allows you to plan out where your actions will go so you can play around with different configurations before spending the time commiting it in-game.
        </p>

        <h3 className={styles.subTitle}>
          How to use this tool to setup your hotbars
        </h3>
        <p>
          Plan out what your WXHB actions could look like when playing Final Fantasy XIV with a gamepad or controller. Use the Job selector to load actions for that class and Drag them into the hotbar slots below like you would in the game. You can even save or share your setups with others using an autogenerated URL.
        </p>
      </div>
    </div>

  );
}

Header.propTypes = {
  selectedJob: PropTypes.shape()
};

Header.defaultProps = {
  selectedJob: null
};
export default Header;
