export interface ClassJobProps {
  Abbr: string,
  Abbreviation: string,
  'Abbreviation@de': string,
  'Abbreviation@fr': string,
  'Abbreviation@ja': string,
  ClassID?: number | null,
  ClassActionAllowlist?: string[],
  Description?: string | null,
  Discipline: string,
  ID: number,
  Icon?: string,
  Name: string,
  'Name@fr': string,
  'Name@de': string,
  'Name@ja': string,
  Role?: string | null,
  Weapon?: string,
  UrlType?: string | null,
}
