export interface ClassJobProps {

  Abbreviation: string,
  'Abbreviation@de': string,
  'Abbreviation@fr': string,
  'Abbreviation@ja': string,
  IsLimitedJob: boolean,
  Name: string,
  'Name@fr': string,
  'Name@de': string,
  'Name@ja': string,
  Role?: string | null,
  ID: number,
  Abbr: string,
  Discipline: string,
  ClassID?: number | null,
  Weapon?: string,
  Description?: string | null,
  Icon?: string,
}
