export interface ClassJobProps {
  Abbr: string,
  Abbreviation: string,
  Abbreviation_de: string,
  Abbreviation_fr: string,
  Abbreviation_ja: string,
  ClassID?: number | null,
  ClassActionAllowlist?: string[],
  Description?: string | null,
  Discipline: string,
  ID: number,
  Icon: string,
  Name: string,
  Name_fr: string,
  Name_de: string,
  Name_ja: string,
  Role?: string | null,
  Url: string,
  Weapon?: string,
  PreIcon?: string,
  UrlType?: string | null,
}
